alvinwan/TexSoup

TexSoup/__init__.py
TexSoup/data.py
TexSoup/reader.py
TexSoup/tex.py
TexSoup/utils.py
tests/test_api.py

Hi!
I was searching for a tool to parse LaTeX, extract some valuable information and then highlight it in the PDF using SyncTeX. To do this, SyncTeX requires line_no:char_no information. I decided to modify your parser to provide such information. Now each token and command name has field "position", which contains the absolute position of its first character in the source file. This absolute position can be converted to line_no:char_no using TexNode.char_pos_to_line function. For more examples, please refer to https://github.com/windj007/TexSoup/blob/master/tests/test_api.py#L36
If you find such functionality useful, please take a look at my changes.
The main idea: everywhere starting from tokenization use not just plain python strings, but strings with offsets. String operations such as …

Navigation to source file

---

TexSoup/reader.py
tests/test_parser.py

Partially fixes #7.
When tokenizing inline math, the `\$` sequence was interpreted as the end of the inline math.

Fix presence of '\$' in '$'-delimited inline math 

---

TexSoup/reader.py
tests/test_parser.py

Fixes #31 
Now macros with arguments on different lines are correctly parsed.

Fix multiline args

---

.gitignore
TexSoup/data.py
tests/test_api.py

Allows the user to search the plain text of a node with a regex. Returns a TokenWithPosition for each match.

Added a regex search function to TexNode

---

TexSoup/__init__.py
TexSoup/data.py
TexSoup/reader.py
TexSoup/tex.py
TexSoup/utils.py
examples/solution_length.py
setup.py
tests/test_parser.py

Adds support for the `\\( ... \\)` and `\\[ ... \\]` shorthand notation for the math and display math environments in LaTeX. Explained in [LaTeX An unofficial reference manual](http://texdoc.net/texmf-dist/doc/latex/latex2e-help-texinfo/latex2e.pdf) at section 16 of the manual. The documentation and tests have been adapted for the changes and other modifications.

Added \( ... \) math environment and \[ ... \] display math environment

---

TexSoup/reader.py

Fix the misspell of latex environment name

multiline -> multline and add missing math environments

---

TexSoup/reader.py
tests/test_parser.py

Hi, 
As the title says I think this fixes #48 and #55 (which are two versions of the same thing). 
Math environments weren't correctly picked up if preceeded by backslash even though after a double backslash they probably should.
I've added a couple of tests to cover each issue. All tests pass.

BUG: Fix #48 and #55 by checking math environment not preceeded by "\\"

---

.travis.yml
setup.py

Hi, thank you for creating and maintaining this nice library :)
This PR mainly removes the test dependencies from the install dependencies. (I also fixed the configuration for TravisCI to keep the status green.)
**Purpose**: Since TexSoup lists `coverage==3.7.1` in its install dependencies, a library depending on TexSoup cannot use other version of `coverage`. I guess that the test dependencies are listed as install dependencies to make everything prepared by running `python setup.py install` on TravisCI. However, to avoid the above-mentioned problem, I suggest removing them from the install dependencies.
**Alternative solution**: I think it would be better to use tox for testing, but that solution requires larger changes. So I chose the hacky way …

Remove test dependencies from install dependencies

---

examples/count_references.py
examples/list_everything.py
examples/resolve_imports.py
examples/simple_conversion.py
examples/structure_diagram.py

I tried to run the scripts in the `examples/` folder and realized they needed little touch ups here and there in order to run. Presumably in an older version `args` was called `arguments`.
Tested on a few sources and they all work now.

Fix examples

---

TexSoup/reader.py

TexSoup is a great idea and it already saved me some boring manual LaTeX work. On the way of looking into another issue I discovered some warnings in the pytest suite that I fixed with this pull request. Some strings were not escaped properly, e.g. `'\lceil'` gives a warning that can easily avoided by using `r'\lceil'` or `'\\lceil'`. However `'\rceil'` gives no warning but inserts a carrige return in the string which is hardly the desired behavior. I fixed those things as well.
Thanks and I'd love to see this project evolving.

Escape backslashes that otherwise lead to warnings or errors.

---

TexSoup/data.py
tests/config.py
tests/samples/pancake.tex
tests/test_load_edit_save.py

I used TexSoup successfully to remove all un-referenced labels from a big LaTeX file. My workflow was:
* Load the document with TexSoup
* Modify the tree with Python
* Save it back to file.
It worked well, however, some parts of the LaTeX file were modified as well, specifically description environments.
```
\begin{description}
\item[egg] white and round
\end{description}
```
gets
```
\begin{description}
\item[egg] eggwhite and round
\end{description}
```
(the text in the square brackets is duplicated).
With this pull request I don't fix the issue but I create a test case that shows the problem (currently it fails as expected).

Test for "load/edit/save" workflow

---

TexSoup/__init__.py
TexSoup/category.py
TexSoup/data.py
TexSoup/reader.py
TexSoup/tex.py
TexSoup/tokens.py
TexSoup/utils.py
examples/list_everything.py
examples/simple_conversion.py
examples/structure_diagram.py
tests/test_parser.py

Major refactoring for parsing:
- Stricter abstraction, dependence on tokens without accessing string values
- More advanced / robust parsing for commands and environments w.r.t. whitespace
- Resolves several outstanding parse issues
- Subsumes #78 
This means all of the following examples can be parsed.
```
\begin
{itemize}
\item hello] there[
\end
{itemize}
```
```
\somecommand
{[}
{]}
```

Refactor parsing

---

TexSoup/reader.py
TexSoup/tokens.py
tests/test_api.py
tests/test_parser.py

- parses math environments, as titled says
- test that checks you can search/replace within math environment
- sets parser mode according to math or not
notes:
- for now, special math characters like `^` or `_` do not induce special behavior. In the future, these should associate super/subscripts with the correct group, accordingly.
- the `mode` is not actually used. This should throw errors if an underscore is left unescaped in not-math mode.
fixes #106

Parse math environments

---

docs/source/navigation.rst

I noticed these two small typos in the docs.
__________
Also, I noticed a surprising aspect of `.contents` including optional args of environments, e.g.
```python
>>> figs = soup.find_all('figure')
>>> fig = figs[0]
>>> fig
\begin{figure}[H]
\centering
\includegraphics[width=0.4\textwidth]{figures/vectors/vector_components.pdf}
\vspace{-2mm}
\caption{	The vector $\vec{v}=(3,2)$ is an arrow in the Cartesian plane.
The horizontal component of $\vec{v}$ is $v_x=3$
and the vertical component  is $v_y=2$.}
\label{fig:vector_components}
\end{figure}
>>> fig.contents
['H',
\centering,
\includegraphics[width=0.4\textwidth]{figures/vectors/vector_components.pdf},
\vspace{-2mm},
\caption{	The vector $\vec{v}=(3,2)$ is an arrow in the Cartesian plane.
The horizontal component of $\vec{v}$ is $v_x=3$ …
```

It's contents not content, and all is only on expr not on nodes

---

TexSoup/reader.py
TexSoup/tokens.py
tests/test_api.py
tests/test_parser.py

> @alvinwan said:
> Is it maybe because of the following line? (maybe should be len(point)?
> `result = text.forward(len(point) + 1) `
Yes indeed. After this change `PunctuationCommandName`s no longer "gobble" the following charaacter and seem to behave as expected.
I've added some tests (if tokens serialize back to string correctly, then they must have been tokenized together as a unit). By coincidence I happened to choose a delimiter `\rfloor` and test was failing... so we ended up with a bonus typo fix.
Last but not least I added three more verbatim-type environments (users can manually add those to `skip_envs` if needed, but seems like a good idea to have them "baked in").

Punctuation commands fix (Issue #111)

---

TexSoup/data.py
TexSoup/reader.py
tests/test_parser.py

Resolves #118 and #131.
This is the current behavior on `master`:
```python
>>> TexSoup.TexSoup(r'\def\foo{bar}')
\def{\}{foo}{bar}
```
It interprets the `\` alone as the first argument, which escapes the brace afterwards and the resulting code will fail with a runaway definition error.
With this patch, I get:
```python
>>> TexSoup.TexSoup(r'\def\foo{bar}')
\def{\foo}{bar}
```
It doesn't quite reproduce the original source, but it will at least render as intended. It also doesn't handle cases of `\def` for commands that take arguments like `\def\foo#1{bar #1}`, but it at least doesn't do any worse than how those are currently handled.

Fix parsing of `\def` without braces around new command name

---

TexSoup/tokens.py
tests/test_parser.py

Resolves #117.
Retain control spaces (`'\ '`), as they change the meaning of the code. For example, some initially valid TeX:
```python
>>> TexSoup.TexSoup(r'\ foo')
\foo
```
becomes an undefined control sequence. With this PR, you get:
```python
>>> TexSoup.TexSoup(r'\ foo')
\ foo
```

Keep control spaces

---

TexSoup/reader.py
tests/test_parser.py

Adds `SIGNATURES` entries for a few common commands that don't take arguments, as suggested by @ivanistheone in multiple issues. Also fixes the fact that these rules are currently ignored inside of named environments (e.g., `equation`).
Resolves #115, resolves #126, resolves #137.

Add/fix some zero-argument signatures

---

TexSoup/data.py
tests/test_api.py

Try to remove from `parent.args` before defaulting to removing from `parent._contents`. Resolves #146.

Properly handle `delete` when in an argument

---

TexSoup/reader.py
TexSoup/tokens.py
tests/test_parser.py

Fixes #135.
When using "special" commands (like `\newcommand`), it's possible to define only one part of an environment (like a singular `\begin{equation}`), which caused errors when parsing. This commit implements a "special" mode, which is entered every time a "special" command is encountered (for now, `\newcommand`, `\renewcommand`, and `\providecommand`), which disables the matching of `\begin{...}` with an associated `\end{...}` until the command considered is fully processed, after which it goes back to normal (non-math) mode. Note that this has the disadvantage that any whole environment defined _inside_ of the special command will not be parsed as an environment, but rather as a series of TeX commands (I think it should be possible to reconstruct a complete env by parsing the …

Fix parsing of environments inside special commands

---

TexSoup/data.py

This PR adds the option to pass [regex flags](https://docs.python.org/3/library/re.html#flags) as a keyword argument to the `search_regex` method. I've also added a docstring to the same method to make the meaning of the `kwargs` argument clearer.

Added regex flags to `search_regex` method
